on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**-dev'

jobs:
  oess_testing:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Run perl-OESS tests
        uses: jonstout/OESS@master
